-- phpMyAdmin SQL Dump
-- version 5.2.1-1.el8
-- https://www.phpmyadmin.net/
--
-- Хост: localhost
-- Время создания: Май 23 2025 г., 05:04
-- Версия сервера: 8.0.41-32
-- Версия PHP: 7.2.24

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `p514771_pets`
--

-- --------------------------------------------------------

--
-- Структура таблицы `market`
--

CREATE TABLE `market` (
  `id` int NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `description` text COLLATE utf8mb4_general_ci NOT NULL,
  `price` float NOT NULL,
  `path` text COLLATE utf8mb4_general_ci NOT NULL,
  `category` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `category_id` int NOT NULL,
  `date` date NOT NULL,
  `nickname` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `avatar_path` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `profile_description` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `user_id` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Дамп данных таблицы `market`
--

INSERT INTO `market` (`id`, `title`, `description`, `price`, `path`, `category`, `category_id`, `date`, `nickname`, `avatar_path`, `profile_description`, `user_id`) VALUES
(7, 'Royal Canin Maxi Adult 15kg', 'Complete feed for dogs - For adult large breed dogs (from 26 to 44 kg) - From 15 months to 5 years old.', 9500, '/web/img/market/67c4697e35517.png', 'dog food', 3, '2025-03-02', 'tali_dog', 'web/img/Proflie/67a72b69b5e23.jpeg', 'Hello! This is my profile', 1),
(8, 'Royal Canin Persian Kitten', 'Royal Canin Persian breed-specific dry kitten food is formulated to meet the nutritional needs of a growing kitten up to 12 months old', 1290, '/web/img/market/67c469a369425.webp', 'cat food', 4, '2025-03-02', 'tali_dog', 'web/img/Proflie/67a72b69b5e23.jpeg', 'Hello! This is my profile', 1),
(9, 'Golden retriever puppy', 'Golden Retrievers are an adaptable breed, meaning they are better at adapting to seasonal changes and various types of climate than certain other breeds. Goldens sport a double-coat, which ensures that these sweet pups are able to tolerate slightly colder temperatures than their friends from other breeds.', 58000, '/web/img/market/67c46a30c4790.jpeg', 'puppies', 11, '2025-03-02', 'tali_dog', 'web/img/Proflie/67a72b69b5e23.jpeg', 'Hello! This is my profile', 1),
(10, 'Royal Canin Golden Retriever Puppy', 'Royal Canin Golden Retriever Puppy dry dog food is designed to meet the nutritional needs of purebred Golden Retrievers 8 weeks to 15 months old', 1270, '/web/img/market/67c46aa46757a.jpg', 'dog food', 3, '2025-03-02', 'tali_dog', 'web/img/Proflie/67a72b69b5e23.jpeg', 'Hello! This is my profile', 1),
(11, 'Royal Canin Joint Care Maxi Dog 10 kg', 'Give your big furry friend the gift of pain-free movement with Royal Canin Joint Care Maxi Dog! Large dogs are more susceptible to joint issues, which can impact their mobility and quality of life. This specially formulated food aids your pet\'s joint health, keeping them happy and active!', 7115, '/web/img/market/67c46d1407a8b.webp', 'dog food', 3, '2025-03-02', 'tali_dog', 'web/img/Proflie/65ae01ecb48e0.jpeg', 'This is my profile', 57),
(12, 'Interactive Cat Toy Tower with Rotating Balls', 'Durable Plastic Three-Level Track and Ball Play Structure, Entertaining and Stimulating Pet Activity Center, No Batteries Needed', 250, '/web/img/market/67c5824b3ce40.webp', 'cat toys', 7, '2025-03-03', 'tali_dog', 'web/img/Proflie/65ae01ecb48e0.jpeg', 'This is my profile', 57),
(15, 'Royal Canin Size Health Nutrition Giant Adult - 15 KG', 'ROYAL CANIN® Giant Adult is meticulously crafted to meet the unique nutritional needs of adult giant breed dogs weighing 45kg and over. This premium dog food is designed to support your giant dog\'s bone, joint, and overall health, ensuring they thrive and maintain their vitality.', 6500, '/web/img/market/67cad366703ff.webp', 'dog food', 3, '2025-03-07', 'mikedog', 'web/img/Proflie/67cac27e43969.jpeg', 'This is my profile', 59),
(16, 'Royal Canin Breed Health Nutrition Adult Shih Tzu Dry Dog Food 1.5kg', 'Royal Canin Dry Food\r\nSpecific Breed: Shih Tzu Adult\r\nOver 10 months old\r\nHealthy Skin: Adult helps support the skin “barrier” role (exclusive complex), maintain skin health (EPA and DHA, vitamin A) and nourish the coat. Enriched with borage oil\r\nDental Health: This formula helps reduce the risk of tartar formation thanks to calcium chelators\r\nStool and  Odour Reduction: This formula helps reduce faecal smell and volume\r\nExclusive Kibble Design: Special Brachycephalic Jaw: A kibble exclusively designed to make it easier for the Shih Tzu to pick up and to encourage him to chew', 965, '/web/img/market/67cd33f1b7bf1.webp', 'dog food', 3, '2025-03-09', 'tali_dog', 'web/img/Proflie/65ae01ecb48e0.jpeg', 'This is my profile', 57),
(22, 'Funny Cat Toy Mouse Sound Squeaky Toys for Pet Cats Kitten Simulation Accessories', 'Size:6*3*2.5CM\r\n\r\n\r\n\r\nPackage:\r\n\r\n1 x toy', 70, '/web/img/market/68246a63e98c0.jpg', 'cat toys', 7, '2025-05-14', 'tali_dog', 'web/img/Proflie/65ae01ecb48e0.jpeg', 'This is my profile', 57),
(23, 'Mewoo - Whack-A-Mole Cat Toy', 'Introduce a world of endless fun for your feline friend with our Whack-A-Mole Cat Toy! This fun, interactive toy features a crafted wooden box with multiple holes, inside which is a variety of elusive \"moles\" for your cat’s playful pouncing. Your pet will be endlessly entertained as they try to catch the moles, which dart in and out randomly, stimulating their natural hunting instincts. This Whack-A-Mole Cat Toy comes with a bag of catnip that can be placed inside the paw design of the toy\'s handles; this provides a long-lasting blissful playtime for cats! Keep your cat active, engaged, and mentally stimulated with this Whack-A-Mole Cat Toy. Perfect for cats at every stage of life, this fun and surprising toy is expertly designed to cater to your purfect baby\'s curiosity while providing a healthy dose of exercise and entertainment.', 2999, '/web/img/market/68246b44ddbfb.webp', 'cat toys', 7, '2025-05-14', 'tali_dog', 'web/img/Proflie/65ae01ecb48e0.jpeg', 'This is my profile', 57),
(24, 'LEGEND SANDY Dog Squeaky Toys for Small Dogs, 12 Pack', '12 PACK PUPPY TOYS FOR ALL OCCASIONS: Various fun in one set! Including 7 pack dog squeaky toys raccoon, monkey, cactus, dog, duck, cow, hedgehog, and 5 pack natural cotton dog rope toys for teething puppies. Great value for the number of cute dog toys you get, which meet different requirements of a dog’s daily life requirements, such as chewing, training, and interactive playing. Whether you participate in the game or not, your dog can be happy, give you a choice to relax', 1837, '/web/img/market/68247f2ea07be.jpg', 'dog toys', 8, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(25, 'Whiskas® Tuna Dry Cat Food 1.2KG', 'WHISKAS® cat food is complete and balanced, specially designed to fulfil your cat’s needs at every life stage. At the age of 12 months, your kitten turns adult, and requires a different nutritional needs. This change in nutritional needs will change again when they turn 7.\r\n\r\nCats aged 1-6 need lots of playtime and a balanced diet to help them stay lean and healthy. Cats are carnivores while humans omnivores, so cats need two times more protein than us. They also need 41 essential nutrients for optimum health. WHISKAS® understands the nutritional needs of cats, and every product is specially designed to be complete and balanced.', 999, '/web/img/market/682480de8c036.png', 'cat food', 4, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(26, 'Whiskas Kitten (2-12 months) Wet Cat Food, Chicken in Gravy 6 Pouches 85 gm each', 'Brand	WHISKAS\r\nFlavour	Chicken\r\nItem Weight	1.02 Kilograms\r\nItem Form	Gravy, Wet\r\nAge Range (Description)	Baby', 2365, '/web/img/market/68248169a9fdf.jpg', 'cat food', 4, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(27, 'Royal Canin Feline Care Nutrition Hair & Skin 85g Cat Wet Food', 'For adult cats\r\nThin slices in gravy\r\nHelps maintain coat beauty\r\nWith omega 3 & omega 6 fatty acids', 75, '/web/img/market/682482021d6ee.jpg', 'cat food', 4, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(28, 'Royal Canin Regular Fit 32 Cat', 'All humans want to stay fit. And so do our cats, despite their eagerness to eat and do nothing. Help maintain your cat’s healthy weight with the high-quality nutrition of Royal Canin Regular Fit 32 Cat.', 2765, '/web/img/market/682482b0e8445.jpeg', 'cat food', 4, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(29, 'Pedigree Complete Nutrition Roasted Chicken, Rice, And Vegetable Dry Dog Food, 14 Lb Bag', 'Dogs bring out the good in us. Pedigree brings out the good in them. Express your love for your dog by serving Pedigree Complete Nutrition Adult Small Dog Dry Dog Food, Chicken, Rice and Vegetable Flavor recipe. This great-tasting dry dog recipe is made with small pieces to meet the unique needs of your small breed dog and contains whole grains, protein, and accents of vegetables. To support your dog’s health and vitality, this dry dog food recipe is formulated with 36 vitamins, minerals, and amino acids. It also contains Omega 6 Fatty Acid and Zinc to help nourish a healthy skin and coat. With no high fructose corn syrup, artificial flavors, or added sugars, Pedigree Complete Nutrition Adult Small Dog Dry Dog Food, Chicken, Rice and Vegetable Flavor shows your dog that you care…and have great taste.', 2173, '/web/img/market/682483371f711.webp', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(30, 'Pedigree Adult Chicken and Vegetables Dry Dog Food 1.5kg', 'Pedigree Adult Dry Dog Food\r\nChicken and Vegetables Flavor\r\nScientifically proven shinier coat in 6 weeks\r\nCalcium and Phosphorous - for strong bones and teeth\r\nDietary Fiber - for digestive system\r\nProtein - for strong muscles\r\nVitamins and Minerals - for strong immune system', 310, '/web/img/market/6824838da9649.webp', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(31, 'Cat grooming Baguio', 'Treat your furry friend to a spa day without leaving the house! ????✨ Our expert groomers come to you, providing top-quality grooming in the comfort of your home. Book now for a stress-free grooming experience!', 2000, '/web/img/market/682486ca52d7c.jpg', 'cat grooming', 2, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(32, 'Vet clinic', 'We provide pet vet services in Baguio City', 1000, '/web/img/market/682487ac9b074.jpg', 'Veterinary', 10, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(33, 'Dog grooming services', 'We provide dog grooming services in Baguio City', 1500, '/web/img/market/682488211477a.jpeg', 'dog grooming', 9, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(34, 'Royal Canin, Canine Care Nutrition Digestive Care Adult Loaf in Sauce - Wet Dog Food', 'Royal Canin, Can Adult - Digestive Care - 385 g\r\n\r\nFounded by a veterinarian, Royal Canin has over 40 years experience in Health Nutrition. Our work with veterinarians, pet nutritionists, breeders and dog professionals from around the world has provided us with knowledge about the specific nutritional requirements of dogs. This knowledge has allowed us to formulate the precise diet for your dogs special needs.', 2300, '/web/img/market/682488a87af66.jpg', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(35, 'Royal Canin Vet Diet Gastro Intestinal Low Fat Dog Food - Can 420g', 'Combination of highly digestible proteins and starches, prebiotics, beet pulp and fish oil helps support digestive security. A low fat concentration improves digestive function in dogs with hyperlipidaemia or with acute pancreatitis. Adjusted levels of soluble/insoluble fibres to help limit fermentations and promote good stools quality. The synergistic antioxidant complex reduces oxidative stress and fights free radicals', 385, '/web/img/market/682489c88fc95.webp', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(36, 'Royal Canin Fiber Canine', 'Increased levels and an optimal blend of soluble and insoluble fibre help maintain intestinal health. Digestive aids help restore the intestinal flora and promote intestinal health. Help reduce inflammation and promote healthy skin and a luxurious coat.', 4000, '/web/img/market/68248a1a65845.webp', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(37, 'Pedigree Beef Dog Food 700g (Can)', '\r\nPedigree Beef Dog Food Can (700g)\r\nAdult Complete Nutrition for Dogs has been reformulated to give grown dogs all the energy and nourishment they need to continue living life to its fullest\r\nThe zinc and linoleic acid in this recipe help keep adult dogs looking like best-in-show winners, and leading levels of antioxidant vitamins E & C work with their immune system to keep them feeling like a puppy', 139, '/web/img/market/68248aa0a268c.webp', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(38, 'Pedigree® Choice Cuts Pouch Adult Wet Dog Food & Meal Topper - 30 Count, Variety Pack', 'Dogs bring out the good in us. Pedigree brings out the good in them. Express your love for your dog by serving Pedigree Choice Cuts In Gravy Adult Soft Wet Dog Food Variety Pack. These great-tasting wet dog food recipes are 100% complete and balanced for adult dogs and are made with real beef or real chicken, bringing a filling and familiar flavor to mealtime. Pedigree Choice Cuts In Gravy Adult Soft Wet Dog Food Variety Pack features three delicious flavors: Hickory Smoked Chicken Flavor, Filet Mignon Flavor, and Beef, Noodles & Vegetables Flavor so your dog can have favorites to choose from. This versatile soft dog food can be served as a topper, mixed with dry dog food, or enjoyed by itself as a complete meal for adult dogs, bringing your dog a variety of ways to indulge. Crafted with no high fructose corn syrup, artificial flavors, or added sugars although, trace amounts may be present due to potential cross-contact at manufacturing, Pedigree Choice Cuts In Gravy Adult Soft Wet Dog Food Variety Pack shows your dog that you care and have great taste.', 1500, '/web/img/market/68248ae5f0440.jpeg', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(39, 'Royal Canin Puppy Mini Wet Puppy Food (1-10kg) - 85 g packs', 'Your puppy\'s growth period is an important life stage; it\'s the time of discovery and change. While your puppy is still growing, it\'s important that its diet supports optimal health. Suitable for puppies aged up to 10 months that will have an adult weight of up to 10kg, ROYAL CANIN Mini Puppy in Gravy is specially formulated with all the nutritional needs of your mini puppy in mind. ROYAL CANIN Mini Puppy in Gravy contains an exclusive complex of antioxidants including vitamin-E to support its juvenile immune system while it\'s still maturing. ROYAL CANIN Mini Puppy in Gravy also contains many beneficial nutrients that help to support your puppy\'s general digestive health. What\'s more, the intense energy content in ROYAL CANIN Mini Puppy in Gravy will meet the high energy needs of your small breed puppy. To cater to each dog\'s individual preferences, ROYAL CANIN Mini Puppy is also available as dry food, with crunchy and tasty kibble. If you\'re considering mixed feeding, simply follow our feeding guidelines to ensure your dog gets an accurate amount of both wet and dry food for optimal benefit.', 389, '/web/img/market/68248ba05cc79.webp', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(40, 'Royal Canin Medium Ageing 7+ Dry Adult Dog Food 15kg', 'As your medium-sized dog enters their later adult years, they may not be as active as they used to be, but they\'ll still typically have their playful, spirited and loyal personality. Therefore, your dog should have a diet that suits their size, age and nutritional needs. For dogs aged over 7 years old, Royal Canin Medium Adult 7+ is a nutritionally complete and balanced formula specially designed to meet your medium dog\'s particular needs and support them throughout the latter stages of adulthood. Designed for medium-sized dogs that weigh between 11 and 25kg, this formula contains a complex of vitamins to help maintain their vitality and overall health. Medium-sized dogs rely on consistent exercise for proper muscle development, and this doesn\'t change as they get older. With its specialised, high-quality protein content, this kibble is crafted to help your adult dog maintain muscle mass.', 4000, '/web/img/market/68248c069f8e2.jpg', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(41, 'Royal Canin Urinary Care Cat Slices in Gravy (12 x 85 g)', 'Cats are known for not drinking enough water. But unfortunately, this can negatively impact their bladder health. That’s why Royal Canin Urinary Care Cat Slices in Gravy tends specifically to your cat\'s urinary function by delivering tailored nutrition.\r\n\r\nThis wet food has an 82% moisture content to promote urine dilution. By lowering chemical concentration, these pouches decrease the risk of bladder stones.  \r\n\r\nNutrition plays a significant role in maintaining healthy mineral levels in the bladder. Royal Canin Urinary Care Cat Slices in Gravy features high-quality nutrients with tailored mineral levels. So your little lion doesn’t have to compromise on nourishment to have a healthy urinary system.\r\n\r\nSince urinary problems are more frequent in overweight cats, this recipe promotes ideal weight maintenance with a carefully adapted calorie content.\r\n\r\nLastly, Royal Canin\'s nutritionists developed this wet cat food to match the macronutrient profile that adult cats instinctively prefer, thereby boosting their well-being.', 2717, '/web/img/market/68248c78c52e0.webp', 'cat food', 4, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(43, 'Royal Canin Veterinary Diet Feline GASTROINTESTINAL canned cat food', 'Specially formulated to assist in the management of gastrointestinal disease in cats requiring a higher energy density.\r\nHigh energy density\r\nSupports digestive health\r\nHelps reduce inflammation\r\nS/O® Index supports urinary health\r\nHigh energy density\r\nHigh energy density to help cats to more easily meet their energy needs\r\n\r\nSupports digestive health\r\nHighly digestible protein, prebiotics and zeolite for improved stool quality\r\n\r\nHelps reduce inflammation\r\nSupplemental omega-3 fatty acids (EPA and DHA) to reduce inflammation in the gastrointestinal tract', 699, '/web/img/market/68248de341bb8.webp', 'cat food', 4, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(44, 'Gastrointestinal 3kg', 'Complete dietetic food for the nutritional management of dogs formulated to reduce acute intestinal absorption disorders, and promote nutritional restoration and convalescence. Highly digestible ingredients. Increased level of electrolytes and essential nutrients. High energy level.', 1600, '/web/img/market/68248e8d2de96.png', 'dog food', 3, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65),
(45, 'Royal Canin, Feline Care Nutrition Oral Care Adult 2.72kg', 'When introducing a new food or treat, it\'s best to allow your pet to adjust gradually. For new food, we recommend a 7-day transition. Begin with a 75:25 ratio of old to new food on Day 1 and Day 2, shifting to a 50:50 mix on Day 3 and Day 4, and a 25:75 balance on Day 5 and Day 6. By Day 7, your pet can fully enjoy their new food. For treats, remember to feed them sparingly — they should constitute no more than 10% of your pet\'s daily caloric intake. Monitor your pet for any unusual reactions when introducing a new treat. Treats are not a substitute for balanced, complete meals.', 2999, '/web/img/market/68248f16d689e.jpg', 'cat food', 4, '2025-05-14', 'Mike_dog', 'web/img/Proflie/68247db1d49d5.jpeg', 'Hi! Welcome to my profile. I love pets', 65);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `market`
--
ALTER TABLE `market`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `market`
--
ALTER TABLE `market`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=48;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
